# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ebe3dfd4b39bce4358297eed079d9128c5f9eef5574ffbd53c99db9deb678b7f78db1852e00e818a7575c6da5f4752a59cc427cba86823b638165959337bb846

test:
  secret_key_base: 75661d87b7b3554a7fcf7f2198195fc8757f9623e795db0c7ed5db1d79b8e7e0a5b26290985d12c886fe219af556fbf97edb0d2476d60f9a0f12959c921e419b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
